apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-runtime-profiler
  labels:
    app.kubernetes.io/name: vulngate-runtime-profiler
    app.kubernetes.io/instance: {{ .Release.Name }}
